#!/bin/sh
# Copyright (c) 2026 陈庄旺.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
# SPDX-License-Identifier: MPL-2.0

echo "执行成功时间：$(date)" > D:/post-push-ran.txt
GOCD_SERVER="139.196.151.15:8153"
REPO_URL="https://gitee.com/wangwang_1_1665527118/emrdocument-engine.git"

# 后台等待推送完成 → 再通知 GoCD
(
    # 等待 push 结束
    read
    curl -X POST "http://$GOCD_SERVER/go/api/admin/materials/git/notify" \
      -H "Accept: application/vnd.go.cd.v2+json" \
      -H "Content-Type: application/json" \
      -d "{\"repository_url\":\"$REPO_URL\"}"
) &

echo "✅ 已通知 GoCD 更新代码"